### ISSUE TITLE
VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#16]
Example test: https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=36464376

```
[WARNING ] /srv/iraf/bldtmp/porcelain.g23AA24Tm8/porcelain/envs/dev/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2699:
VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or
function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
```

**Comment by mcara** [comment]
@pllim @stsci-hack This warning is not due to the code in the ``drizzlepac`` itself but rather due to ``stsci.convolve`` - see https://github.com/spacetelescope/stsci.convolve/issues/5

Once https://github.com/spacetelescope/stsci.convolve/pull/6 is merged, ``drizzlepac`` will no longer issue these warnings.

**Comment by mcara** [comment]
Solved by merging https://github.com/spacetelescope/stsci.convolve/pull/6
