### ISSUE TITLE
TypeError: buffer is too small for requested array

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#23]
Example test: https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=36462995

```
Trailer file written to:  stis_01_1visit

  File "/Users/shared/iraf_conda/bldtmp/porcelain.phEUcEl55g/porcelain/envs/dev/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/shared/iraf_conda/bldtmp/porcelain.phEUcEl55g/porcelain/envs/dev/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/iraf/rt/betadrizzle/stis/stis_01/stis_01.py", line 72, in stis_01
    astrodrizzle.AstroDrizzle('o*flt.fits',runfile=testname,configobj=parObj)
  File "/Users/shared/iraf_conda/bldtmp/porcelain.phEUcEl55g/porcelain/envs/dev/lib/python2.7/site-packages/drizzlepac/astrodrizzle.py", line 123, in AstroDrizzle
    run(configObj, wcsmap=wcsmap)
  File "/Users/shared/iraf_conda/bldtmp/porcelain.phEUcEl55g/porcelain/envs/dev/lib/python2.7/site-packages/drizzlepac/util.py", line 229, in wrapper
    raise errorobj
TypeError('buffer is too small for requested array',)
```

**Comment by mcara** [comment]
I have investigated the cause of this crash and it is due to:
1. a previous crash left a corrupted ``STISFUV-MAMA_1024x1024_1_staticMask.fits`` file in the test directory (it has too little data compared to what is expected);
2. a combination of software changes that made the code susceptible to the presence of corrupt static mask files in the working directory: AND
   * In the [Changeset 7537](https://trac.stsci.edu/ssb/stsci_python/changeset/7537/development/trunk/BigBlackBox/lib/staticMask.py) code was made to overwrite existing static mask files *only* ``if not(fileutil.checkFileExists(filename))``, that is, never (CC: @sosey ).
   * In the [Changeset 32128](https://trac.stsci.edu/ssb/stsci_python/changeset/32128/drizzlepac/trunk/lib/drizzlepac/staticMask.py) in which I have removed randomization of static mask file names (at INS request). This change in itself is not harmful except when combined with previously mentioned code that does not permit overwriting existing mask files (an important detail that I missed).

So, an easy fix for the tests is to remove the offending corrupt static mask from the test's directory. However, the true fix should fix the code to overwrite existing static masks.

At this time it is important to further investigate the code to understand the consequences of modifying the code before this test can be fixed @sosey .

**Comment by mcara** [comment]
@stsci-hack What is your opinion on overwriting existing static mask files?

**Comment by sosey** [comment]
wow, 9 years ago. jeez

**Comment by mcara** [comment]
@sosey I know 😆

**Comment by pllim** [comment]
@sosey , you can never get rid of your drizzlepac past...

**Comment by mcara** [comment]
Hotel California?

**Comment by sosey** [comment]
I think way back then there was a lot of discussion about when or even if to overwrite mask files and the arguments went back and forth. This blackbox branch was a playground for the move of multidrizzle to astrodrizzle way before drizzlepac!  Guessing that the logic was added cause only new masks were made when none existed on disk, so when write came around they didn't want to overwrite.  Warren might remember more  of the discussion around this.

**Comment by stsci-hack** [comment]
Go ahead and overwrite the static mask files.

**Comment by mcara** [comment]
Solved in https://github.com/spacetelescope/drizzlepac/issues/24
