### ISSUE TITLE
points were outside the output image

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#32]
I see a lot of "*nnn* points were outside the output image" warnings. If they can be ignored, then just close this.

**Comment by mcara** [comment]
Yes, these messages indicate that some pixels from *input images*, when resampled onto *output reference image* (either the one created by astrodrizzle or the one provided by the user), lie outside the borders of the output image. This is quite typical when users provide their own reference images that are too small but it can also happen when drizzlepac automatically generates a reference image because the algorithm is a "0-order" in accuracy and, e.g., does not account for "curvature" of images borders when the image is undistorted. In the later case (astrodrizzle-generated reference image) a few pixels may be outside. Usually this does not have any serious consequences unless your science target is at the border/corner of the input image.

**Comment by mcara** [comment]
So, if you see *a lot* of pixels lying outside *when astrodrizzle generates a reference image* then we have a real issue, but for 100-1000 pixels it is OK and the issue can be closed.

**Comment by pllim** [comment]
Here are the ones exceeded 1000 points:

```
1782 points were outside the output image.

    drizzlepac: stis/stis_03/stis_03.stis_03


1865 points were outside the output image. 

    drizzlepac: acs/wfc/acs_tweak/test.acs_tweak
    drizzlepac: acs/wfc/acs_tweak/test.test_pixsky1


225533 points were outside the output image.

    drizzlepac: acs/hrc/acs_kernels/acs_kernels.test
```

**Comment by mcara** [comment]
I would not worry even about 2000 points. However, the last example deserves an investigation.

**Comment by OlyDLG** [comment]
@pllim: if/when it's not terribly inconvenient, can you please detail how to reproduce the result of the last example?  Thanks!

**Comment by mcara** [comment]
@OlyDLG To reproduce (at least roughly) the results of the tophat test, get the ``J8BT06040`` dataset from [MAST](http://archive.stsci.edu/hst/search.php) (you should get a file named ``j8bt06nyq_flt.fits``)
and do the following:
```python
>>> from drizzlepac import astrodrizzle
>>> from stwcs import updatewcs
>>> updatewcs.updatewcs("j8bt06nyq_flt.fits", checkfiles=False)
>>> astrodrizzle.AstroDrizzle("j8bt06nyq_flt.fits", clean=True, runfile=astrodrizzle.log,
... mdriztab=False, num_cores=1, in_memory=True, skysub=False, driz_sep_wcs=False,
... driz_separate=False, median=False, blot=False, driz_cr=False, driz_combine=True,
... final_kernel="tophat", output="driz_tophat.fits")
```
WARNINIG: the above instructions have not been tested so some tweaking may be required.

**Comment by OlyDLG** [comment]
Thanks!

**Comment by OlyDLG** [comment]
Follow-up: so, I have the astropy distributed with the standard (free) anaconda3 distro, which appears not to have drizzlepac (among other stsci components).  Recommendation(s)?  (E.g., Download and install "astroconda"?

**Comment by mcara** [comment]
@OlyDLG You can start by reading this page http://drizzlepac.stsci.edu. On that page you will find links to the [AstroConda distribution](http://astroconda.readthedocs.io/en/latest/), examples for running ``drizzlepac`` tasks, and at the bottom of the page there is a "SUPPORT" section providing a link to the [drizzlepac forum](forum.stsci.edu) as well as the e-mail to the STScI help desk: help@stsci.edu where your questions will be redirected to the appropriate people.
