### ISSUE TITLE
Failed tests: Two tests have unanticipated changed results

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#38]
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=summary&qid=5749

**Comment by mcara** [comment]
@pllim @stsci-hack In my opinion opening issues about failing tests (in addition to the cron job notifications that we receive) is over the top. In addition, to being non-issue, it only clutters the log.

By the way, it is not a bug as the changes are due to "release" of ``stwcs`` and failure of some tests was *anticipated*.

**Comment by pllim** [comment]
Ok

**Comment by pllim** [comment]
@mcara , still failing. Did you OK the new "truth" images?

**Comment by mcara** [comment]
@pllim I did ~40 min ago. I had to discuss this with @nden and @stsci-hack 

@pllim Just so you know, after ``acs_tweak`` is OKified, *expect* ``pixsky1`` to fail next day, so please do not open another issue.

**Comment by pllim** [comment]
Well, one more day of shaming then. :wink:

**Comment by mcara** [comment]
@pllim For your peace of mind, I just okified the two failing pixsky1 tests so expect all tests to be passing tomorrow.
