### ISSUE TITLE
Alignment issue found in custom-generated ACS 10265_01 drizzled-combined images

### ISSUE THREAD

**Issue by dulude** [spacetelescope/drizzlepac#392]
Found slight systemic misalignment when comparing images hst_10265_01_acs_wfc_f606w_j92c01_drc.fits and hst_10265_01_acs_wfc_total_j92c01_drc.fits from /grp/hst/ssb/artifactory/hst_10265_01_dev_catalog.zip.

At this point, it is not known which image is in fact correctly aligned and which image is misaligned, just that some sort of systemic misalignment exists.

**Comment by stsci-hack** [comment]
This misalignment stems from a difference in the final output WCS that was defined for each case.  The file 'hst_10265_01_acs_wfc_total_j92c01_drc.fits' was created using 'final_refimage=None' and was used as the refimage for creating the other image.  This was expected to generate identical images since the input images are identical between the 2 products.  

The fact that there was a misalignment, though, indicates a problem with how the final_refimage WCS gets interpreted or defined in one of the cases.

**Comment by nden** [comment]
Given the date of filing the ticket, should it be closed?
