### ISSUE TITLE
Segmentation catalog only includes data from first chip

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/drizzlepac#546]
Evaluating the initial processing results in HLALAB1 for 'ib6wd6', it turns out that the UVIS segmentation catalogs only include sources in the lower half (chip 1?) of the field for (at least) the F555W and F336W catalogs.  

I created region files using: 
```
  seg = Table.read(ecsv_file, format='ascii.ecsv')
  reg = seg['RA', 'DEC']
  reg.write(ecsv_file.replace('.ecsv', '.reg'), format='ascii.no_header')

```
Reviewing the point catalogs demonstrates that they include sources covering the entire field of view.  So, it is not clear whether this is something specific to this field of view or generic for the segmentation catalog generation.

**Comment by mdlpstsci** [comment]
While waiting for some data to process I took a look at output for ib4606 from November.  The segment catalog for the UVIS total and UVIS f555w indicate sources on both chips.  I will take a look at this dataset processed with current software.

**Comment by mdlpstsci** [comment]
Oops.  Hit the wrong button!

**Comment by mdlpstsci** [comment]
Just processed the same dataset as above, but now only chip 1 has sources indicated.  A bug was clearly introduced at some point.  This bug is apparently not dataset specific.

**Comment by mdlpstsci** [comment]
The problem is caused by the footprint mask used by the segment catalog to define the illuminated portion of the image.

**Comment by mdlpstsci** [comment]
Only the segmentation catalog (not the point catalog) uses a mask to define the illuminated portion of the image.  Since only the first chip is present in the WFC3 mask, sources were only identified in this single chip of the total image.  The problem has been isolated to the code which computes image footprints, and not the computation of the meta_wcs.  The cell_utils.py module has undergone a lot of upgrades so a previous version of the module was utilized to aid in isolating the problem.  Use of an older cell_utils.py module reproduced the correct mask.

**Comment by mdlpstsci** [comment]
The previous version of the SkyFootprint build method worked properly for generating a binary mask to indicate illuminated/non-illuminated portions of the WFC3 images.  However, this method was modified to use the PIL capabilities, and effectively, the data from [SCI,1] (Chip 2) is being overwritten by the data from [SCI,4] (Chip 1), so the final output image only contains Chip 1 information.
