### ISSUE TITLE
Tweakback does not use the correct WCS from the drz image

### ISSUE THREAD

**Issue by Vb2341** [spacetelescope/drizzlepac#848]
When attempting to use tweakback to align flcs corresponding to an already aligned drc, the incorrect WCS is used as the "final" WCS.  Tweakback incorrectly selects the "OPUS" wcs rather than the wcs that is (typically) labeled "TWEAK", this is I believe due to an issue in the line below:

https://github.com/spacetelescope/drizzlepac/blob/ed0bded8ba37fd47d5ba67e6a2ba6cb66d0aea7c/drizzlepac/tweakback.py#L180

The last key in wcskeys is 'O', referring to the OPUS WCS.  This is in contrast to the wnames returned by `stwcs.wcsutil.altwcs.wcsnames()`.  

I tested this with an image I drizzled:
`wcsutil.altwcs.wcsnames('f336w_wlm-galaxy-pos2_wfc3_uvis_dn012_drc.fits', 1)` returns
`{'O': 'OPUS', 'A': 'IDC_2731450pi', ' ': 'TWEAK'}`

While `wcsutil.altwcs.wcskeys('f336w_wlm-galaxy-pos2_wfc3_uvis_dn012_drc.fits', 1)` returns
`[' ', 'A', 'O']`

While there is logic to actually choose the correct key, provided the `wcsname` argument is provided, this logic seems to be ignored in the line referenced.  I think the fix is fairly straightforward (just putting the referenced line properly in each of the two cases in the if/else blocks just above), but currently this makes tweakback unusable.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-446](https://jira.stsci.edu/browse/HLA-446)._

**Comment by astrophysaxist** [comment]
Currently facing this bug too.

**Comment by astrophysaxist** [comment]
> Currently facing this bug too

It looks like I was facing a slightly different bug that likely deals with the ordering of the keys that get returned. My workaround was to manually specify the `newname` argument as the WCSNAME value of the drizzled file and to manually pass that as the `wcsname` argument as well.

**Comment by stsci-hack** [comment]
Problems with using 'tweakback' have been investigated for quite some time.  One issue which may affect this issue was resolved with the merging of #913 , while a more recent effort was undertaken with #1372 to provide an improved interface to tweakback with the hopes of making it easier for users to run successfully.  These PRs should resolve the issue reported here.  If not, we can re-open this issue.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-446?focusedCommentId=606141#comment-606141):_

Problems with using 'tweakback' have been investigated for quite some time. One issue which may affect this issue was resolved with the merging of [#&#x2060;913](https://github.com/spacetelescope/drizzlepac/pull/913) , while a more recent effort was undertaken with [#&#x2060;1372](https://github.com/spacetelescope/drizzlepac/pull/1372) to provide an improved interface to tweakback with the hopes of making it easier for users to run successfully. These PRs should resolve the issue reported here. If not, we can re-open this issue.
