### ISSUE TITLE
Catalog generation - fix comparison of number of good sources to total sources 

### ISSUE THREAD

**Issue by mdlpstsci** [spacetelescope/drizzlepac#855]
Fix comparison of number of good sources to total sources when the number of good sources is 0 and the threshold is 0.0.
In catalog_utils.py (verify_crthresh()):

               `all_sources = len(source_cat)
                log.info("{} catalog with {} good sources out of {} total sources :  CR threshold = {}".format(cat_type, n_sources, all_sources, thresh))
                if n_sources < thresh:    
                    reject_catalogs = True
                    log.info("{} catalog FAILED CR threshold.  Rejecting both catalogs...".format(cat_type))
                    break`

if n_sources < thresh   SHOULD BE   if n_sources <= thresh.  This is the only change necessary for proper running  of the code.

Use datasets j8eg04, j8mq50, and j9qu06 for testing.  They are all variations on the same theme, and it would be good to know they all work properly with the fix.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-827](https://jira.stsci.edu/browse/HLA-827)._

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-827?focusedCommentId=610838#comment-610838):_

*Dataset J8MQ50:* There are non-zero sources found for all catalogs, so the 
```java
(A) n_sources <= thresh or (B) n_sources < thresh```
is never true, and the if block is never executed. These are results based upon caldp_mvmdrizzzle_rc5 plus any other code updates done on master versus.   The "old" code is (B), and the updated code is (A).  The DR?.fits and ECSV files are identical, and in this case, there are sources.

*Dataset J8EG04:*  There are no good sources found, so the output catalogs are empty of measurements.  As for the previous dataset, the DR?.fits and the ECSV files are identical.  There are no sources found.  Since there are no sources found in any catalog, the processing does not drop through into the block of code which contains the change.

*Dataset J9QU06:* There are sources found in this dataset, so the processing properly fails the "if" statement (as is the case for the J8MQ50 dataset). Comparing the results before and after the fix, the DR?.fits and ECSV files are identical.

Despite what this ticket and [GitHub Drizzlepac #&#x2060;855 ](https://github.com/spacetelescope/drizzlepac/issues/855)say, only the **J8EG04** dataset is a good for testing this fix.  Ack - see next comment as the code to be fixed is never reached by any of these datasets.
```java
 ```

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-827?focusedCommentId=611001#comment-611001):_

**Dataset J8EG04**

It is already determined before getting to the block of code with the statement in question that there are no sources.  This line of code is not executed though it still should be corrected.  The code proceeds to process without problems.

There is only one source in the field and in the total image, it appears to be mis-aligned.  I will need to follow-up and check the issue in the Slack channel to see what the actual "issue" reported was.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-827?focusedCommentId=611193#comment-611193):_

After not finding this issue discussed in the Slack channel, I realized the [GitHub Drizzlepac #&#x2060;855 ](https://github.com/spacetelescope/drizzlepac/issues/855)is from November 2020.  The datasets quoted in the ticket which indicate they are good for testing a fix no longer even execute the apparent troublesome portion of the code.  The entirety of the drizzlepac code has changed a great deal in two years.  Since this has not been noted to have been an issue and no longer fails for the datasets suggested, I will make a modest change in the code which covers the case of zero sources.

**Comment by nden** [comment]
Jira ticket resolved. Closing

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-827](https://jira.stsci.edu/browse/HLA-827)._

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-827?focusedCommentId=610838#comment-610838):_

*Dataset J8MQ50:* There are non-zero sources found for all catalogs, so the 
```java
(A) n_sources <= thresh or (B) n_sources < thresh```
is never true, and the if block is never executed. These are results based upon caldp_mvmdrizzzle_rc5 plus any other code updates done on master versus.   The "old" code is (B), and the updated code is (A).  The DR?.fits and ECSV files are identical, and in this case, there are sources.

*Dataset J8EG04:*  There are no good sources found, so the output catalogs are empty of measurements.  As for the previous dataset, the DR?.fits and the ECSV files are identical.  There are no sources found.  Since there are no sources found in any catalog, the processing does not drop through into the block of code which contains the change.

*Dataset J9QU06:* There are sources found in this dataset, so the processing properly fails the "if" statement (as is the case for the J8MQ50 dataset). Comparing the results before and after the fix, the DR?.fits and ECSV files are identical.

Despite what this ticket and [GitHub Drizzlepac #&#x2060;855 ](https://github.com/spacetelescope/drizzlepac/issues/855)say, only the **J8EG04** dataset is a good for testing this fix.  Ack - see next comment as the code to be fixed is never reached by any of these datasets.
```java
 ```
