### ISSUE TITLE
Drizzled images contain remnants of OPUS WCS

### ISSUE THREAD

**Issue by mcara** [spacetelescope/drizzlepac#863]
When a drizzled image is created, OPUS WCS is usually removed. However, not all OPUS WCS keywords are removed and some are left over. Take a look at the header provided in https://github.com/spacetelescope/drizzlepac/issues/862#issue-742103149, specifically at the line:

```
RADESYSO= 'ICRS'               / Equatorial coordinate system                   
```

This is the only keyword left over from the OPUS WCS from the input images. However, it is enough to trick `altwcs.wcskeys()` to detect `'O'` as a key and then produce the crash described in https://github.com/spacetelescope/stwcs/pull/165 when attempting to align drizzled images (created with `build=True` option) in `tweakreg`.

`drizzlepac` should thoroughly remove **all** OPUS WCS keywords from the output image.

**Comment by mcara** [comment]
This issue, however, quite possibly could be a bug in `stwcs` and not in the `drizzlepac`. Until this clear, let's keep this issue open here.

CC: @stsci-hack @nden

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-451](https://jira.stsci.edu/browse/HLA-451)._

**Comment by rjavila** [comment]
@mcara asked me to post about this issue here. 

I drizzled some ACS and WFC3/IR visits together. The drizzled products were aligned to GAIA. When trying to use *tweakback* the ACS images crashed (WFC3 images ran fine). We tracked the problem down to the RADESYS0 and WCSTYPE0 header keywords were still present in the ACS images. Removing the two keywords fixed the problem. The WFC3 images do have the WCSTYPE0 keyword left over.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-451?focusedCommentId=570620#comment-570620):_

The problems with ACS data stem from the default rules file in FITSBLENDER for ACS including the OPUS WCS keywords in the section for populating the HDRTAB.  Defining a keyword to be added to the HDRTAB without specifying a rule for that keyword in the next section causes that keyword to MOVE to the HDRTAB deleting it from the output header itself.  However, the rules file for ACS included a section for adding all the OPUS WCS keywords (like CD1_1O) to the HDRTAB.  This caused the call the `STWCS.ALTWCS.readAltWCS()` function as used by `DRIZZLEPAC.WCS_FUNCTIONS.removeAllAltWCS()` function to clean up the output header to not recognize that there were still OPUS WCS keywords still in the output header since only the RADESYSO keyword was present.  This keyword, though, was enough to trip up subsequent STWCS.ALTWCS functions into thinking there was still a complete WCS solution with the key='O' (OPUS WCS) as reported for this ticket.

WFC3 data did not suffer from this problem due to the fact that the rules file for WFC3 data in FITSBLENDER does not add the OPUS WCS keywords to the HDRTAB at all.   

Fortunately, the only solution required for this problem is to redefine the rules file for ACS in the FITSBLENDER package to remove specification of the OPUS WCS keywords or to add RADESYSO to the list of keywords (depending on whether the ACS team wants those original OPUS WCS keywords in the HDRTAB or not).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-451?focusedCommentId=571232#comment-571232):_

The ACS team has agreed to simply remove the OPUS WCS keywords from the HDRTAB portion of the ACS rules file as the way to resolve this ticket.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-451?focusedCommentId=571360#comment-571360):_

[Fitsblender PR #&#x2060;32](https://github.com/spacetelescope/fitsblender/pull/32) has been submitted and merged to implement the solution agreed upon by the ACS team (specifically, Roberto).  [Fitsblender PR #&#x2060;31](https://github.com/spacetelescope/fitsblender/pull/31) filed on 6-Feb will remain open In case subsequent testing still encounters problems.  Should no further problems be reported, then #&#x2060;31 will be closed without being merged in as it would no longer be needed.
