### ISSUE TITLE
updatewcs

### ISSUE THREAD

**Issue by orifox** [spacetelescope/drizzlepac#901]
Hi,

When I don't have updatewcs set, I get an error to set it:
ValueError: 'fname' must be a file object opened in 'update' mode.

When I do have upatewcs set, I get the following error:
ValueError: Undefined variable `iref' in string `iref$2731450pi_idc.fits'

Thanks,
Ori

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-471](https://jira.stsci.edu/browse/HLA-471)._

**Comment by stsci-hack** [comment]
Hello Ori,

It is not clear from the information in this ticket what code you were trying to run that called `updatewcs` or how you were trying to call this code.  However, the first error comes from passing in a filename (as a string) instead of opening the file with `astropy.io.fits.open()` with `mode="update"`.  The second error indicates that you do not have the environment variable `iref` set to point to a local directory where the code can find the reference files specified in the image header, in this case, the distortion model reference file `2731450pi_idc.fits`.  You can get these reference files using the web service [https://hst-crds.stsci.edu/bestrefs/](https://hst-crds.stsci.edu/bestrefs/).  

Should you continue to struggle to run this code, please contact 'help@stsci.edu' with more details about what code you were running and how you were trying to call this code.  

Cheers,
Warren

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-471?focusedCommentId=606140#comment-606140):_

Provided user with information to resolve their problem on 17-Dec-2020.  No subsequent response by user, so assuming issue was resolved.
